FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        curl \
        tesseract-ocr \
        poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Production hardening: install from the pinned lock file (exact versions,
# generated by pip-compile) rather than requirements-docker.txt's loose >=
# ranges, so a rebuild six months from now can't silently pull in a newer,
# untested, or supply-chain-compromised transitive dependency. requirements.txt/
# requirements-docker.txt remain the human-edited source of intent; the .lock
# files are regenerated deliberately (`pip-compile requirements.txt -o
# requirements.lock.txt`) whenever a dependency is actually added or upgraded.
COPY requirements.txt requirements-docker.txt requirements.lock.txt requirements-docker.lock.txt ./
RUN pip install -r requirements-docker.lock.txt

COPY app ./app
COPY workers ./workers

RUN mkdir -p /app/data

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
